### ISSUE TITLE
[WSL2] can't open vs-code with button to open the sample container

### ISSUE THREAD

**Issue by mellester** [docker/dev-environments#43] opened 2021-08-05 09:07 UTC
**Describe the bug**
I can not open vs-code with button to open the container

**To Reproduce**
I am using Docker for windows with the WSL2 integration .
I start the single container sample and press the button after its started 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/609138/128322566-7ea3a208-ba41-4a5a-b712-3576fc60b885.png)

**Desktop (please complete the following information):**
 - Windows 10 pro
 - 19043.1110

**Additional context**
Docker engine 19043.1110
WSL2 integration enabled

**Comment by mellester** [comment] 2021-08-05 09:09
Possible duplicate https://github.com/docker/dev-environments/issues/28

**Comment by glours** [comment] 2021-08-05 09:09
Duplicate of #30

**Closed by glours** 2021-08-05 09:09 UTC
Labels: bug
