### ISSUE TITLE
Docker Desktop Dev Environment & Git Stuck State with no way to interact with the process to approve...

### ISSUE THREAD

**Issue by archoda** [docker/dev-environments#40] opened 2021-08-03 16:23 UTC
**Describe the bug**
Initialized a dev environment create request using gitHub SSH pathway. It's stuck in QA state with the following log:

**"RSA key fingerprint is SHA256:##############################

**To Reproduce**
1. Open Docker Desktop (For Mac)
2. Click on 'Dev Environments'
3. Click on textfield in the upper right hand corner and enter in private git ssh path
4. Click on the 'Create' button
5. After a short time, click on the environment record, read the log it's stuck in terminal Q/A of 

**Expected behavior**
Expected a clear and complete outcome of a git repo to run an environment.

**Screenshots**

**Desktop (please complete the following information):**
 - OSX, Big Sur
 - Version 11.4

**Additional context**
![Screen Shot 2021-08-03 at 12 24 31 PM](https://user-images.githubusercontent.com/4642545/128051815-d53a45b2-3a24-4936-bf00-301579f8309a.png)

**Comment by webark** [comment] 2021-08-03 17:39
I believe this is a similar issue/duplicate of #37

**Comment by webark** [comment] 2021-08-03 19:51
yep

**Comment by glours** [comment] 2021-08-03 19:54
Ok so I'll close this one to keep only the #37

**Closed by glours** 2021-08-03 19:54 UTC
Labels: bug
