### ISSUE TITLE
Docker Dev Enviroments Does not support custom directory installs. 

### ISSUE THREAD

**Issue by Alauraa** [docker/dev-environments#16] opened 2021-07-01 03:35 UTC
As the name states, if you install in a custom directory, docker will not be able to detect it.

**Comment by chris-crone** [comment] 2021-07-05 08:27
Hi @Alauraa. Is this a duplicate of [this issue](https://github.com/docker/dev-environments/issues/14)?

**Comment by nebuk89** [comment] 2021-07-05 08:44
@Alauraa if you fancy giving us some direct feedback or chatting to the team on a call drop me an email on bengotch@docker.com :D

**Comment by Alauraa** [comment] 2021-07-07 04:52
So, It's not a copy of that persay, well not at all, say if i were to Visual Studio Code in a custom directory, say ( Z:/Applications/Visual Studio Code, ) Even with the stable version of docker downloaded and installed, it will not detect visual studio code installed, it will simply keep saying in the setting's pane "Install" and you can move out of it and use docker normally, but if its on a custom partition, say as said the (Z) drive, it won't physically work, (At least from what i have seen).

So in theory it could be my PC acting up, but when i install say on the (C:) drive, it works just fine, therefore either the program doesn't see or notice it is installed, or it simply refuses to plug and or to locate the install to use said VSC's Install, and this is with the plugin installed and enabled in the custom directory, when you close out of docker, say full stop and close out of it, when it reopens, it still gives the same error, which makes no sense since your restarting the entire application to see if it see's any changes with installed applications on the host system. 

So in the end, i do not know if it is to do with my PC and or to do with me installing it in custom directories, but when it is on the (C:) drive, it works fine, when its installed on another drive that is not the main windows partition, docker will refuse to see it and will prompt you to install it and refuse to work until you install it on the (C:) drive.

**Closed** 2022-06-22 07:43 UTC
Labels: bug
